# Generated by Django 5.1.6 on 2025-08-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='heading',
            field=models.CharField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_url',
            field=models.URLField(blank=True, max_length=2047),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subheading',
            field=models.CharField(blank=True, max_length=1023),
        ),
    ]
