# Generated by Django 5.1.6 on 2025-06-20 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginSignUp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
