# Generated by Django 5.1.6 on 2025-08-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_chathistory_delete_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='bot_response',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='user_message',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='chats',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='session_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
