# Generated by Django 5.1.6 on 2025-04-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mentalHealthForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('mental_health_concerns', models.CharField(max_length=200)),
                ('consulted_before', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('preferred_mode_of_therapy', models.CharField(choices=[('online', 'Online'), ('in_person', 'In-person'), ('not_sure', 'Not sure yet')], max_length=20)),
                ('best_contact_time', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=10)),
                ('problem_description', models.TextField()),
                ('agree_to_policy', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
