# Generated by Django 5.1.6 on 2025-04-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultationForm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mentalHealthForm',
            new_name='ConsultationForm',
        ),
    ]
