# Generated by Django 5.1.6 on 2025-05-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultationForm', '0002_rename_mentalhealthform_consultationform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationform',
            name='best_contact_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='consultationform',
            name='consulted_before',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='consultationform',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='consultationform',
            name='preferred_contact_method',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='consultationform',
            name='preferred_mode_of_therapy',
            field=models.CharField(max_length=20),
        ),
    ]
