# Generated by Django 5.1.6 on 2025-08-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultationForm', '0003_alter_consultationform_best_contact_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationform',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultationform',
            name='problem_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
